environment = "dev"
project     = "ToTheNew"
vpc_security_group_ids  = [""]
disable_api_termination = false
image_id                = ""
key_name                = "tothenew"
cluster_name    = "eks_cluster"
node_group_name = "eks_node_group"
subnet_ids      = ["subnet-999999999999", "subnet-999999999999", "subnet-999999999999"]
instance_types  = ["t3.medium", "t2.medium"]
desired_size    = 2
max_size        = 4
min_size        = 1
